services:
  mongodb:
    image: mongo:7.0
    container_name: vite-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: viteapp
    volumes:
      - mongodb_data:/data/db
    networks:
      - vite-network

  redis:
    image: redis:7.2-alpine
    container_name: vite-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - vite-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: vite-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - vite-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  vite-network:
    driver: bridge